kopenDjango/urls.py
#-*- coding: utf-8 -*-
"""
kopenDjango Social network to share sales promotions
https://github.com/jfmedeirosneto/kopendjango
Copyright(c) 2016 João Neto <jfmedeirosneto@yahoo.com.br>
"""
from django.conf.urls import patterns, include
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^kopenDjango/', include('kopenDjango.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Admin
    (r'^admin/', include(admin.site.urls)),
    
    # Media
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),    
    
    # Index
    (r'^$', 'kopenDjango.base.views.index'),
    (r'^noscript/$', 'kopenDjango.base.views.noscript'),    
    (r'^dialog_contact_form/$', 'kopenDjango.base.views.dialog_contact_form'),
    (r'^contact_form/$', 'kopenDjango.base.views.contact_form'),
    
    # Links usuario
    (r'^dialog_change_user/$', 'kopenDjango.usuario.views.dialog_change_user'),
    (r'^dialog_user_points/$', 'kopenDjango.usuario.views.dialog_user_points'),
    (r'^dialog_top_users/$', 'kopenDjango.usuario.views.dialog_top_users'),
    (r'^dialog_login/$', 'kopenDjango.usuario.views.dialog_login'),
    (r'^dialog_request_password/$', 'kopenDjango.usuario.views.dialog_request_password'),
    (r'^dialog_register_user/$', 'kopenDjango.usuario.views.dialog_register_user'),
    (r'^dialog_change_password/(?P<user_id>\d+)/(?P<password_hash>[0-9a-f]+)/$', 'kopenDjango.usuario.views.dialog_change_password'),    
    (r'^dialog_termos_uso/$', 'kopenDjango.usuario.views.dialog_termos_uso'),
    (r'^login/$', 'kopenDjango.usuario.views.login'),    
    (r'^request_password/$', 'kopenDjango.usuario.views.request_password'),
    (r'^logout/$', 'kopenDjango.usuario.views.logout'),        
    (r'^register/$', 'kopenDjango.usuario.views.register'),
    (r'^change_user/$', 'kopenDjango.usuario.views.change_user'),
    (r'^change_password/$', 'kopenDjango.usuario.views.change_password'),
    (r'^facebook_authorize/$', 'kopenDjango.usuario.views.facebook_authorize'),
    
    # Links produtos
    (r'^dialog_add_oferta/$', 'kopenDjango.produto.views.dialog_add_oferta'),
    (r'^dialog_report_oferta/$', 'kopenDjango.produto.views.dialog_report_oferta'),
    (r'^ajax_produtos/$', 'kopenDjango.produto.views.ajax_produtos'),
    (r'^ajax_locais/$', 'kopenDjango.produto.views.ajax_locais'),
    (r'^ajax_check_local/$', 'kopenDjango.produto.views.ajax_check_local'),
    (r'^ajax_check_produto/$', 'kopenDjango.produto.views.ajax_check_produto'),
    (r'^ajax_oferta/$', 'kopenDjango.produto.views.ajax_oferta'),    
    (r'^busca/$', 'kopenDjango.produto.views.busca'),
    (r'^oferta/$', 'kopenDjango.produto.views.oferta'),
    (r'^oferta_shared/$', 'kopenDjango.produto.views.oferta_shared'),
    (r'^oferta_commented/$', 'kopenDjango.produto.views.oferta_commented'),        
    (r'^busca_shared/$', 'kopenDjango.produto.views.busca_shared'),
    (r'^oferta_like/$', 'kopenDjango.produto.views.oferta_like'),
    (r'^oferta_dislike/$', 'kopenDjango.produto.views.oferta_dislike'),
    (r'^oferta_notify/$', 'kopenDjango.produto.views.oferta_notify'),
    (r'^add_oferta/$', 'kopenDjango.produto.views.add_oferta'),
    (r'^report_oferta/$', 'kopenDjango.produto.views.report_oferta'),
    (r'^local_searched/$', 'kopenDjango.produto.views.local_searched'),
)

kopenDjango/base/models.py
#-*- coding: utf-8 -*-
"""
kopenDjango Social network to share sales promotions
https://github.com/jfmedeirosneto/kopendjango
Copyright(c) 2016 João Neto <jfmedeirosneto@yahoo.com.br>
"""
from django.db import models

# Create your models here.

kopenDjango/cidade/models.py
#-*- coding: utf-8 -*-
"""
kopenDjango Social network to share sales promotions
https://github.com/jfmedeirosneto/kopendjango
Copyright(c) 2016 João Neto <jfmedeirosneto@yahoo.com.br>
"""
from django.db import models

class Cidade(models.Model):
    nome = models.CharField('Nome',
                            max_length=128,
                            help_text=u'Nome da cidade.')
    active = models.BooleanField('Ativo',
                                 default=True,
                                 help_text=u'Cidade ativa.')        
    
    def __unicode__(self):
        return self.nome    
    
    class Meta:
        verbose_name = u'Cidade'
        verbose_name_plural = u'Cidades'
        ordering = ['nome']

kopenDjango/django_evolution/models.py
try:
    from django.utils.timezone import now
except ImportError:
    from datetime import datetime
    now = datetime.now

from django.db import models


class Version(models.Model):
    signature = models.TextField()
    when = models.DateTimeField(default=now)

    class Meta:
        ordering = ('-when',)
        db_table = 'django_project_version'

    def __unicode__(self):
        if not self.evolutions.count():
            return u'Hinted version, updated on %s' % self.when

        return u'Stored version, updated on %s' % self.when


class Evolution(models.Model):
    version = models.ForeignKey(Version, related_name='evolutions')
    app_label = models.CharField(max_length=200)
    label = models.CharField(max_length=100)

    class Meta:
        db_table = 'django_evolution'

    def __unicode__(self):
        return u"Evolution %s, applied to %s" % (self.label, self.app_label)

kopenDjango/produto/models.py
#-*- coding: utf-8 -*-
"""
kopenDjango Social network to share sales promotions
https://github.com/jfmedeirosneto/kopendjango
Copyright(c) 2016 João Neto <jfmedeirosneto@yahoo.com.br>
"""
from django.db import models

import random, datetime

from kopenDjango.stdimage.fields import StdImageField
from kopenDjango.usuario.models import Usuario
from kopenDjango.cidade.models import Cidade
from kopenDjango.base.utils import timenow

class Produto(models.Model):
    nome = models.CharField('Nome',
                            max_length=140,
                            help_text=u'Nome do produto.')
    imagem = StdImageField('Imagem',
                           size=(220, 220),
                           thumbnail_size=(50, 50),
                           upload_to='produto',
                           blank=True,
                           null=True,
                           help_text=u'Imagem do produto.')
    active = models.BooleanField('Ativo',
                                 default=True,
                                 help_text=u'Produto ativo.')
    suggested = models.BooleanField('Sugerido',
                                    default=False,
                                    help_text=u'Produto ativo.')
    created = models.DateTimeField('Criado',
                                   default=timenow)
    modified = models.DateTimeField('Modificado',
                                    default=timenow)
        
    def save(self, *args, **kwargs):
        self.nome = self.nome.title()
        self.modified = timenow()
        super(Produto, self).save(*args, **kwargs)
    
    def __unicode__(self):
        return self.nome    
    
    class Meta:
        verbose_name = u'Produto'
        verbose_name_plural = u'Produtos'
        ordering = ['nome']
        
class Local(models.Model):
    nome = models.CharField('Nome',
                            max_length=140,
                            help_text=u'Nome do local.')
    imagem = StdImageField('Imagem',
                           size=(220, 220),
                           thumbnail_size=(50, 50),
                           upload_to='local',
                           blank=True,
                           null=True,
                           help_text=u'Imagem do local.')
    active = models.BooleanField('Ativo',
                                 default=True,
                                 help_text=u'Local ativo.')
    searched = models.DecimalField('Searched',
                                   max_digits=12,
                                   decimal_places=0,
                                   default=0,
                                   help_text=u'Número de buscas.')    
    created = models.DateTimeField('Criado',
                                   default=timenow)
    modified = models.DateTimeField('Modificado',
                                    default=timenow)
        
    def save(self, *args, **kwargs):
        self.nome = self.nome.title()
        self.modified = timenow()
        super(Local, self).save(*args, **kwargs)

    def get_popularidade(self):
        value = self.searched
        ofertaQuery = self.ofertas.filter(active=True);
        if ofertaQuery.count() > 0:
            value = value + ofertaQuery.count()
            for ofertaObject in ofertaQuery:
                value = value + ofertaObject.get_popularidade()
        return int(value)
    get_popularidade.short_description = 'Popularidade'   
    
    def __unicode__(self):
        return self.nome    
    
    class Meta:
        verbose_name = u'Local'
        verbose_name_plural = u'Locais'
        ordering = ['nome']        

class OfertaActiveManager(models.Manager):
    def get_query_set(self):
        #Retorna query ja tratado
        month_ago = timenow() - datetime.timedelta(days=30)
        return super(OfertaActiveManager, self).get_query_set().\
            filter(active=True,
                   produto__active=True,
                   user__active=True,
                   local__active=True).\
            exclude(created__lt=month_ago)
     
class Oferta(models.Model):
    produto = models.ForeignKey(Produto,
                                help_text=u'Produto da oferta.',
                                related_name='ofertas')
    user = models.ForeignKey(Usuario,
                             help_text=u'Usuário que criou a oferta.',
                             related_name='ofertas')
    cidade = models.ForeignKey(Cidade,
                               help_text=u'Cidade da oferta.',
                               related_name='ofertas')    
    local = models.ForeignKey(Local,
                              help_text=u'Local da oferta.',
                              related_name='ofertas')
    imagem = StdImageField('Imagem',
                           size=(220, 220),
                           thumbnail_size=(50, 50),
                           upload_to='oferta',
                           blank=True,
                           null=True,                               
                           help_text=u'Imagem da oferta.')        
    preco = models.DecimalField('Preço',
                                max_digits=7,
                                decimal_places=3,
                                help_text=u'Preço normal do produto.')    
    active = models.BooleanField('Ativo',
                                 default=True,
                                 help_text=u'Oferta ativa.')
    promoted = models.BooleanField('Promovida',
                                   default=False,
                                   help_text=u'Oferta de anunciante.')
    new = models.BooleanField('Nova',
                              default=True,
                              help_text=u'Oferta nova.')
    notify = models.BooleanField('Notifica',
                                 default=True,
                                 help_text=u'Notifica usuário.')    
    shared = models.DecimalField('Shared',
                                 max_digits=12,
                                 decimal_places=0,
                                 default=0,                               
                                 help_text=u'Número de compartilhamentos.')
    commented = models.DecimalField('Commented',
                                    max_digits=12,
                                    decimal_places=0,
                                    default=0,
                                    help_text=u'Número de comentários.')    
    liked = models.DecimalField('Liked',
                                max_digits=12,
                                decimal_places=0,
                                default=0,
                                help_text=u'Número de gostaram.')
    disliked = models.DecimalField('Disliked',
                                   max_digits=12,
                                   decimal_places=0,
                                   default=0,
                                   help_text=u'Número de não gostaram.')  
    searched = models.DecimalField('Searched',
                                   max_digits=12,
                                   decimal_places=0,
                                   default=0,
                                   help_text=u'Número de buscas.')
    viewed = models.DecimalField('Viewed',
                                 max_digits=12,
                                 decimal_places=0,
                                 default=0,
                                 help_text=u'Número de visualizações.')    
    created = models.DateTimeField('Criado',
                                   default=timenow)
    modified = models.DateTimeField('Modificado',
                                    default=timenow)

    objects = models.Manager() #Default manager (deve ser o primeiro para nao gerar erro ao salvar objeto)
    active_objects = OfertaActiveManager() #Filtra ativos
   
    def get_imagem_url(self):
        if self.imagem:
            return self.imagem.url
        elif self.produto.imagem:
            return self.produto.imagem.url
        else:
            return "/static/sem_imagem.png"
            
    def get_thumb_imagem_url(self):
        if self.imagem:
            return self.imagem.thumbnail.url()
        elif self.produto.imagem:
            return self.produto.imagem.thumbnail.url()
        else:
            return "/static/sem_imagem.thumbnail.png"
        
    def get_imagem_width(self):
        if self.imagem:
            return self.imagem.width
        elif self.produto.imagem:
            return self.produto.imagem.width
        else:
            return 80        
        
    def get_imagem_height(self):
        if self.imagem:
            return self.imagem.height
        elif self.produto.imagem:
            return self.produto.imagem.height
        else:
            return 80        
        
    def get_thumb_imagem_width(self):
        h_factor = 50.0/self.get_imagem_width()
        v_factor = 50.0/self.get_imagem_height()
        factor = min(h_factor, v_factor)
        if self.imagem:
            return int(factor*self.imagem.width)
        elif self.produto.imagem:
            return int(factor*self.produto.imagem.width)
        else:
            return 50        
        
    def get_thumb_imagem_height(self):
        h_factor = 50.0/self.get_imagem_width()
        v_factor = 50.0/self.get_imagem_height()
        factor = min(h_factor, v_factor)        
        if self.imagem:
            return int(factor*self.imagem.height)
        elif self.produto.imagem:
            return int(factor*self.produto.imagem.height)
        else:
            return 50        
    
    def get_popularidade(self):
        value = self.shared + self.commented + self.liked - self.disliked
        return int(value)
    get_popularidade.short_description = 'Popularidade'    
    
    def get_visualizacoes(self):
        value = self.viewed 
        return int(value)

kopenDjango/usuario/models.py
#-*- coding: utf-8 -*-
"""
kopenDjango Social network to share sales promotions
https://github.com/jfmedeirosneto/kopendjango
Copyright(c) 2016 João Neto <jfmedeirosneto@yahoo.com.br>
"""
from django.db import models

from kopenDjango.base.utils import timenow

class Usuario(models.Model):
    user = models.CharField('Usuário',
                            max_length=32,
                            help_text=u'Nome de usuário.')
    name = models.CharField('Nome completo',
                            max_length=200,
                            help_text=u'Nome completo.')    
    email = models.EmailField('E-mail',
                            max_length=200,
                            help_text=u'Endereço de e-mail.')    
    password = models.CharField('Senha',
                            max_length=32,
                            help_text=u'Senha para acesso.')
    facebook_id = models.BigIntegerField('Facebook Id',
                                         default=0,
                                         help_text=u'Facebook Id.')
    active = models.BooleanField('Ativo',
                                 default=True,
                                 help_text=u'Usuário ativo.')
    points = models.IntegerField('Pontuação',
                                 default=50,
                                 help_text=u'Pontuação do usuário.')    
    failures = models.IntegerField('Falhas de login',
                                   default=0,
                                   help_text=u'Falhas de logins.')    
    created = models.DateTimeField('Criado',
                                   default=timenow)
    modified = models.DateTimeField('Modificado',
                                    default=timenow)
    password_hash = models.CharField('Hash',
                            null=True,
                            max_length=512,
                            help_text=u'Password Hash.')    

    def save(self, *args, **kwargs):
        self.modified = timenow()
        super(Usuario, self).save(*args, **kwargs)
                
    def __unicode__(self):
        return self.user    
    
    class Meta:
        verbose_name = u'Usuário'
        verbose_name_plural = u'Usuários'
        ordering = ['user']        
    

kopenDjango/cidade/views.py
"""
kopenDjango Social network to share sales promotions
https://github.com/jfmedeirosneto/kopendjango
Copyright(c) 2016 João Neto <jfmedeirosneto@yahoo.com.br>
"""

kopenDjango/templates/ajax_oferta.html
{% load tags_produtos %}
<div class="ui-grid-solo">
    <div class="ui-block-a">
        {% if oferta.active %}
        {{ oferta.preco|format_currency }}<br/>
        {% else %}
        <span style="color: red;">* Oferta Desativada</span><br/>
        <span style="color: red;"><del>{{ oferta.preco|format_currency }}</del></span><br/>
        {% endif %}
        {{ oferta.produto.nome }}
    </div>
</div>
<div class="ui-grid-a" style="width: 200px; margin: auto; padding: 20px 5px 10px 5px;">
	<div class="ui-block-a" id="id_div_like" liked="{{ liked }}" style="position: relative;">
		<a style="width: 40px; padding-left: 15px;" id="id_botao_like" href="{{ protocol }}{{ domain }}/oferta_like/?id={{ oferta.id }}&csrfmiddlewaretoken={{ csrf_token }}" rel="nofollow" cookie="__OpinouOferta__{{ oferta.id }}" data-role="button" data-icon="thumbs_up" data-iconpos="notext" data-inline="true" data-mini="true" title="Gostei"></a>
	</div>
	<div class="ui-block-b" id="id_div_dislike" disliked="{{ disliked }}" style="position: relative;">
		<a style="width: 40px; padding-left: 15px;" id="id_botao_dislike" href="{{ protocol }}{{ domain }}/oferta_dislike/?id={{ oferta.id }}&csrfmiddlewaretoken={{ csrf_token }}" rel="nofollow" cookie="__OpinouOferta__{{ oferta.id }}" data-role="button" data-icon="thumbs_down" data-iconpos="notext" data-inline="true" data-mini="true" title="Não Gostei"></a>
	</div>
</div>	
<div class="ui-grid-b">
	<div class="ui-block-a" style="width: 15%; text-align: left;">
		{% if previous_id %}<a style="height: 40px; padding-top: 15px;" id="id_botao_previous" href="#" rel="nofollow" oferta="#id_link_oferta_{{ previous_id }}" data-role="button" data-mini="true" data-icon="arrow-l" data-iconpos="notext" title="Oferta Anterior">Oferta Anterior</a>{% endif %}			
	</div>
	<div class="ui-block-b" style="width: 70%; text-align: center;">
		<a id="id_link_local_oferta" href="http://www.google.com/search?q={{ oferta.local.nome|urlify }}+{{ oferta.cidade.nome|urlify }}" rel="nofollow" callback="{{ protocol }}{{ domain }}/local_searched/?id={{ oferta.local.id }}&csrfmiddlewaretoken={{ csrf_token }}" data-role="button" data-mini="true" title="Procurar Local {{ oferta.local }} {{ oferta.cidade }}">{{ oferta.local }}<br/>{{ oferta.cidade }}</a>
	</div>
	<div class="ui-block-c" style="width: 15%; text-align: right;">
		{% if next_id %}<a style="height: 40px; padding-top: 15px;" id="id_botao_next" href="#" rel="nofollow" oferta="#id_link_oferta_{{ next_id }}" data-role="button" data-mini="true" data-icon="arrow-r" data-iconpos="notext" title="Próxima Oferta">Próxima Oferta</a>{% endif %}			
	</div>
</div>
<div class="ui-grid-solo" style="padding: 10px 0px 0px 0px;">
	<div class="ui-block-a">
		<img width="{{ oferta.get_imagem_width }}" height="{{ oferta.get_imagem_height }}" alt="{{ oferta.produto.nome }}" src="{{ protocol }}{{ domain }}{{ oferta.get_imagem_url }}"/>
	</div>
</div>
<div class="ui-grid-b" style="width: 200px; margin: auto;">	
	<div class="ui-block-a" style="text-align: right;">
		<a style="width: 40px; padding-left: 15px;" id="id_botao_facebook" target="_blank" href="http://www.facebook.com/sharer.php?u={{ protocol }}{{ domain }}/oferta/?id={{ oferta.id }}" rel="nofollow" callback="{{ protocol }}{{ domain }}/oferta_shared/?id={{ oferta.id }}&csrfmiddlewaretoken={{ csrf_token }}" data-role="button" data-icon="facebook" data-iconpos="notext" data-inline="true" data-mini="true" title="Compartilhar no Facebook"></a>
	</div>
	<div class="ui-block-b" style="text-align: left;">
		<a style="width: 40px; padding-left: 15px;" id="id_botao_twitter" target="_blank" href="http://twitter.com/home?status=Gostei da oferta &quot;{{ oferta.produto.nome }}&quot; - {{ protocol }}{{ domain }}/oferta/?id={{ oferta.id }}" rel="nofollow" callback="{{ protocol }}{{ domain }}/oferta_shared/?id={{ oferta.id }}&csrfmiddlewaretoken={{ csrf_token }}" data-role="button" data-icon="twitter" data-iconpos="notext" data-inline="true" data-mini="true" title="Compartilhar no Twitter"></a>
	</div>
	<div class="ui-block-c" style="text-align: left;">
		<a style="width: 40px; padding-left: 15px;" id="id_botao_google_plus" target="_blank" href="https://plus.google.com/share?url={{ protocol }}{{ domain }}/oferta/?id={{ oferta.id }}" rel="nofollow" callback="{{ protocol }}{{ domain }}/oferta_shared/?id={{ oferta.id }}&csrfmiddlewaretoken={{ csrf_token }}" data-role="button" data-icon="google_plus" data-iconpos="notext" data-inline="true" data-mini="true" title="Compartilhar no Google+"></a>
	</div>	
</div>
<div class="ui-grid-solo">
    <div class="ui-block-a">
        <a id="id_botao_go_home" href="{{ protocol }}{{ domain }}/?busca={{ oferta.produto.nome|urlify }}" data-role="button" data-mini="true" data-inline="true" rel="external" data-ajax="false" data-theme="e" title="Outras Ofertas {{ oferta.produto.nome }}">Outras Ofertas<br/>{{ oferta.produto.nome }}</a>
    </div>
</div>
<div class="ui-grid-solo">
    <div class="ui-block-a">
	   <a id="id_botao_report" href="{{ protocol }}{{ domain }}/dialog_report_oferta/?id={{ oferta.id }}" rel="nofollow" data-role="button" data-icon="report" data-iconpos="left" data-inline="true" data-mini="true" data-rel="dialog" title="Informar Erro">Informar Erro</a>
    </div>
</div>
<div class="ui-grid-solo" style="padding: 10px 0px 0px 0px;">
    <div class="ui-block-a">
        Adicionada {{ oferta.created|date:"d/m/Y" }}
        {% if oferta.promoted %}
        <br/><span style="color: red;">* Oferta de Anunciante</span>
        {% endif %}
        {% if oferta.new %}
        <br/><span style="color: red;">* Oferta Nova</span>
        {% endif %}
    </div>
</div>

kopenDjango/templates/dialog_add_oferta.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block body_content %}
<!-- Dialog Adiciona Oferta -->
<div id="id_dialog_add_oferta" data-role="dialog" data-close-btn="right" data-overlay-theme="a" style="text-align: center;">
    <div data-role="header" data-theme="c"><h1>Adicionar Oferta</h1></div>            
    <div data-role="content" data-theme="c" style="overflow: visible;">
	{% if kopen_user %}
    	<div id="id_form_error5" class="form_error"></div>
    	<form id="id_form_add_oferta" action="{{ protocol }}{{ domain }}/add_oferta/" method="post">
    		{% csrf_token %}
    		<div style="display: none;"><input name="user_id" value="{{ kopen_user.id }}" type="hidden" /></div>
    		<label for="id_cidade2">Cidade</label>
            <select name="cidade" id="id_cidade2" required="required" data-native-menu="false" data-mini="true">
            	<option value="-1" data-placeholder="true">Selecione uma Cidade</option>
        		{% for c in cidades %}{% if c.active %}{% if forloop.counter == 1 %}
        		<option value="{{ c.id }}" selected="selected">{{ c.nome }}</option>
				{% else %}
        		<option value="{{ c.id }}">Oferta para {{ c.nome }}</option>
				{% endif %}{% endif %}{% endfor %}
            </select>
            <label for="id_produto">Produto</label>            
            <div style="position: relative;">
                <div class="suggestionsBox" id="id_busca_produtos_add" style="display: none;">
                    <ul class="suggestionList" id="id_busca_produtos_add_list"></ul>
                    <img width="10" height="10" src="{{ protocol }}{{ domain }}{% static "downarrow.png" %}"/>                    
                </div>
            </div>
			<input name="produto" id="id_produto" ajax_produtos="{{ protocol }}{{ domain }}/ajax_produtos/" ajax_check_produto="{{ protocol }}{{ domain }}/ajax_check_produto/" placeholder="Produto para adicionar oferta (Ex. Gasolina)" value="" type="search" required="required" autocomplete="off" data-mini="true"/>
            <label for="id_local">Local</label>			
            <div style="position: relative;">
                <div class="suggestionsBox" id="id_busca_locais_add" style="display: none;">
                    <ul class="suggestionList" id="id_busca_locais_add_list"></ul>
                    <img width="10" height="10" src="{{ protocol }}{{ domain }}{% static "downarrow.png" %}"/>                    
                </div>
            </div>
            <input name="local" id="id_local" ajax_locais="{{ protocol }}{{ domain }}/ajax_locais/" ajax_check_local="{{ protocol }}{{ domain }}/ajax_check_local/" placeholder="Local da oferta (Ex. Posto 7)" value="" type="search" required="required" autocomplete="off" data-mini="true"/>
            <label for="id_preco">Preço R$</label>
            <input name="preco" id="id_preco" onkeypress="return isNumberKey(event);" placeholder="Preço Ofertado (Ex. 2,759)" value="" type="text" required="required" autocomplete="off" data-mini="true"/>                    
            <input name="submit" value="Adicionar Oferta" type="submit" data-theme="b" data-mini="true"/>
		</form>			
	{% else %}
		<h3>Para adicionar uma Oferta você precisa entrar!</h3>
		<a href="{{ protocol }}{{ domain }}/dialog_login/" rel="nofollow" data-rel="dialog" data-role="button" data-inline="true" data-mini="true" data-theme="b">Entrar</a>
		<a href="{{ protocol }}{{ domain }}/dialog_register_user/" rel="nofollow" data-rel="dialog" data-role="button" data-inline="true" data-mini="true" data-theme="b">Novo por aqui? Registre-se</a>
	{% endif %}            	
    </div>
</div>
{% endblock %}

kopenDjango/templates/dialog_facebook_authorize.html
{% extends "base.html" %}

{% block body_content %}
<!-- Dialog Facebook Authorize -->
<div id="id_dialog_facebook_authorize" data-role="dialog" data-close-btn="none" data-overlay-theme="a" style="text-align: center;">
	<div data-role="header" data-theme="c"><h1>Facebook</h1></div>
	<!-- Container para conteudo dinamico -->
	<div data-role="content" data-theme="c">
		{% if message %}<p>{{ message }}</p>{% endif %}
    </div>
</div>
{% if redirect %}<script type="text/javascript">
setTimeout(function() {
	window.location.href = "{{ redirect }}";
}, 2000);	
</script>{% endif %}
{% endblock %}

kopenDjango/templates/dialog_request_password.html
{% extends "base.html" %}
{% block body_content %}
<!-- Dialog Request Password -->
<div id="id_dialog_request_password" data-role="dialog" data-close-btn="right" data-overlay-theme="a" style="text-align: center;">
    <div data-role="header" data-theme="c"><h1>Nova Senha</h1></div>            
    <div data-role="content" data-theme="c">
    	<div id="id_form_error6" class="form_error"></div>
    	<form id="id_form_request_password" action="{{ protocol }}{{ domain }}/request_password/" method="post">
    		{% csrf_token %}
            <label for="id_email">E-mail</label>
            <input name="email" id="id_email" placeholder="E-mail" value="" type="email" required="required" autocomplete="off" data-mini="true"/>
            <input name="submit" value="Solicitar" type="submit" data-theme="b" data-mini="true"/>
		</form>
    </div>
</div>
{% endblock %}